name: cpp-linter
on:
  pull_request:
    branches: [main, master, develop]
    paths:
      [
        "**.c",
        "**.cpp",
        "**.h",
        "**.hpp",
        "**.cxx",
        "**.hxx",
        "**.cc",
        "**.hh",
        "**CMakeLists.txt",
        "meson.build",
        "**.cmake",
      ]
  push:
    branches: [main, master, develop]
    paths:
      [
        "**.c",
        "**.cpp",
        "**.h",
        "**.hpp",
        "**.cxx",
        "**.hxx",
        "**.cc",
        "**.hh",
        "**CMakeLists.txt",
        "meson.build",
        "**.cmake",
      ]

jobs:
  cpp-linter:
    permissions:
      issues: write
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ninja
        run: sudo apt-get install ninja-build -y

      - name: Set up Compilation Database
        run: cmake --preset Debug

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: "file" # Use .clang-format config file.
          tidy-checks: "" # Use .clang-tidy config file.
          files-changed-only: false
          tidy-review: true
          format-review: true
          database: "./build/compile_commands.json"
          thread-comments: true
          ignore: "build"

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
