name: test_and_coverage
on:
  pull_request:
    branches: [main, master, develop]
    paths:
      [
        "**.c",
        "**.cpp",
        "**.h",
        "**.hpp",
        "**.cxx",
        "**.hxx",
        "**.cc",
        "**.hh",
        "**CMakeLists.txt",
        "meson.build",
        "**.cmake",
      ]
  push:
    branches: [main, master, develop]
    paths:
      [
        "**.c",
        "**.cpp",
        "**.h",
        "**.hpp",
        "**.cxx",
        "**.hxx",
        "**.cc",
        "**.hh",
        "**CMakeLists.txt",
        "meson.build",
        "**.cmake",
      ]

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build coverage container
        run: docker compose -f docker/coverage.docker-compose.yml build --no-cache
      - name: Run coverage container
        run: docker compose -f docker/coverage.docker-compose.yml up
      - name: Docker compose down
        run: docker compose -f docker/coverage.docker-compose.yml down
      - name: Print coverage report
        run: cat ./build/coverage.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          files: ./build/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
